import { FwdError } from '../errors.js';
import { commands, optionsFor } from './index.js';

/** @typedef {import('./common.js').Completion} Completion */
/** @typedef {Exclude<Completion, 'commands'>} Candidates Completion with command names filled in. */

/**
 * The parts of the command definitions that completion scripts need.
 */
function model() {
  const visible = commands.filter((cmd) => !cmd.hidden);
  const names = visible.map((cmd) => cmd.name);
  // Command names are fixed when the script is generated.
  /** @type {(c: Completion) => Candidates} */
  const resolve = (c) => (c === 'commands' ? names : c);
  return {
    commands: visible.map((cmd) => ({
      name: cmd.name,
      summary: cmd.summary,
      positionals: (cmd.positionals ?? []).map(resolve),
      options: Object.entries(optionsFor(cmd)).map(([name, opt]) => ({
        flag: `--${name}`,
        help: opt.help,
        takesValue: opt.type === 'string',
        complete: opt.complete && resolve(opt.complete),
      })),
    })),
    // Flags whose next word is a value, not a positional argument.
    valueFlags: [
      ...new Set(
        visible.flatMap((cmd) =>
          Object.entries(optionsFor(cmd))
            .filter(([, opt]) => opt.type === 'string')
            .map(([name]) => `--${name}`),
        ),
      ),
    ],
  };
}

/** @param {string} text */
function quote(text) {
  return `'${text.replaceAll("'", `'\\''`)}'`;
}

/**
 * Shell code (bash and zsh share the syntax) producing candidate words.
 * @param {'hosts' | 'ports'} completion
 */
function wordsCommand(completion) {
  return completion === 'hosts'
    ? 'fwd __complete hosts 2>/dev/null'
    : 'fwd __complete ports "${host[@]}" 2>/dev/null';
}

// Shared by bash and zsh: walk the words before the cursor, counting
// positional arguments and noting --host so `ports` uses the right host.
/**
 * @param {ReturnType<typeof model>} m
 * @param {string} words The shell's array of words.
 * @param {number} first Index of the first word after the subcommand.
 * @param {string} current Index of the word being completed.
 */
function scanWords(m, words, first, current) {
  return `  for ((i = ${first}; i < ${current}; i++)); do
    case \${${words}[i]} in
      --host) host=(--host "\${${words}[i+1]}"); ((i++)) ;;
      ${m.valueFlags.filter((f) => f !== '--host').join('|')}) ((i++)) ;;
      -*) ;;
      *) ((pos++)) ;;
    esac
  done`;
}

/** @param {ReturnType<typeof model>} m */
function bash(m) {
  /** @param {Candidates} c */
  const words = (c) => (Array.isArray(c) ? c.join(' ') : `$(${wordsCommand(c)})`);
  const cases = m.commands.map((cmd) => {
    const values = cmd.options
      .filter((o) => o.takesValue)
      .map((o) => (o.complete ? `${o.flag}) words="${words(o.complete)}" ;;` : `${o.flag}) return ;;`));
    const positionals = cmd.positionals.map((c, i) => `${i}) words="${words(c)}" ;;`);
    return `    ${cmd.name})
      opts=${quote(cmd.options.map((o) => o.flag).join(' '))}
      case $prev in ${values.join(' ')} *) case $pos in ${positionals.join(' ')} esac ;; esac ;;`;
  });
  return `# bash completion for fwd. Generated by \`fwd completion bash\`.
_fwd() {
  local cur=\${COMP_WORDS[COMP_CWORD]} prev=\${COMP_WORDS[COMP_CWORD-1]} cmd=\${COMP_WORDS[1]}
  local opts='' words='' i pos=0 host=()
  if ((COMP_CWORD == 1)); then
    COMPREPLY=($(compgen -W ${quote(`${m.commands.map((c) => c.name).join(' ')} --help --version`)} -- "$cur"))
    return
  fi
${scanWords(m, 'COMP_WORDS', 2, 'COMP_CWORD')}
  case $cmd in
${cases.join('\n')}
  esac
  if [[ $cur == -* ]]; then
    COMPREPLY=($(compgen -W "$opts" -- "$cur"))
  else
    COMPREPLY=($(compgen -W "$words" -- "$cur"))
  fi
}
complete -F _fwd fwd
`;
}

/** @param {ReturnType<typeof model>} m */
function zsh(m) {
  /** @param {Candidates} c */
  const words = (c) => (Array.isArray(c) ? `(${c.join(' ')})` : `(\${(f)"$(${wordsCommand(c)})"})`);
  /** @param {{ name: string, help: string }[]} items */
  const described = (items) => items.map((i) => quote(`${i.name}:${i.help}`)).join(' ');
  const cases = m.commands.map((cmd) => {
    const values = cmd.options
      .filter((o) => o.takesValue)
      .map((o) => (o.complete ? `${o.flag}) vals=${words(o.complete)} ;;` : `${o.flag}) return ;;`));
    const positionals = cmd.positionals.map((c, i) => `${i}) vals=${words(c)} ;;`);
    return `    ${cmd.name})
      opts=(${described(cmd.options.map((o) => ({ name: o.flag, help: o.help })))})
      case $prev in ${values.join(' ')} *) case $pos in ${positionals.join(' ')} esac ;; esac ;;`;
  });
  return `#compdef fwd
# zsh completion for fwd. Generated by \`fwd completion zsh\`.
_fwd() {
  local cmd=\${words[2]} prev=\${words[CURRENT-1]} i pos=0
  local -a host opts vals
  if ((CURRENT == 2)); then
    local -a cmds=(${described(m.commands.map((c) => ({ name: c.name, help: c.summary })))})
    _describe -t commands command cmds
    return
  fi
${scanWords(m, 'words', 3, 'CURRENT')}
  case $cmd in
${cases.join('\n')}
  esac
  if [[ \${words[CURRENT]} == -* ]]; then
    _describe -t options option opts
  else
    compadd -a vals
  fi
}
if [[ \${zsh_eval_context[-1]} == loadautofunc ]]; then
  _fwd "$@"
else
  compdef _fwd fwd
fi
`;
}

/** @param {ReturnType<typeof model>} m */
function fish(m) {
  /** @param {Candidates} c */
  const words = (c) =>
    Array.isArray(c) ? quote(c.join(' ')) : `'(fwd __complete ${c}${c === 'ports' ? ' (__fwd_host)' : ''} 2>/dev/null)'`;
  /** @param {string} cmd */
  const seen = (cmd) => `__fish_seen_subcommand_from ${cmd}`;
  const lines = [
    '# fish completion for fwd. Generated by `fwd completion fish`.',
    '',
    '# Number of positional arguments before the cursor, after the subcommand.',
    'function __fwd_pos',
    '    set -l n 0',
    '    set -l skip 0',
    '    for t in (commandline -opc)[3..-1]',
    '        if test $skip = 1',
    '            set skip 0',
    '        else if contains -- $t ' + m.valueFlags.join(' '),
    '            set skip 1',
    "        else if not string match -q -- '-*' $t",
    '            set n (math $n + 1)',
    '        end',
    '    end',
    '    echo $n',
    'end',
    '',
    '# "--host <host>" if given on the command line, for completing saved ports.',
    'function __fwd_host',
    '    set -l tokens (commandline -opc)',
    '    if set -l i (contains -i -- --host $tokens); and set -q tokens[(math $i + 1)]',
    '        echo --host',
    '        echo $tokens[(math $i + 1)]',
    '    end',
    'end',
    '',
    'complete -c fwd -f',
    "complete -c fwd -n __fish_use_subcommand -s h -l help -d 'Show help'",
    "complete -c fwd -n __fish_use_subcommand -s v -l version -d 'Show the version'",
    ...m.commands.map((c) => `complete -c fwd -n __fish_use_subcommand -a ${c.name} -d ${quote(c.summary)}`),
  ];
  for (const cmd of m.commands) {
    lines.push('');
    for (const o of cmd.options) {
      const value = o.takesValue ? ` -x${o.complete ? ` -a ${words(o.complete)}` : ''}` : '';
      lines.push(`complete -c fwd -n '${seen(cmd.name)}' -l ${o.flag.slice(2)}${value} -d ${quote(o.help)}`);
    }
    cmd.positionals.forEach((c, i) => {
      lines.push(`complete -c fwd -n '${seen(cmd.name)}; and test (__fwd_pos) -eq ${i}' -a ${words(c)}`);
    });
  }
  return `${lines.join('\n')}\n`;
}

const generators = { bash, zsh, fish };

/** @type {import('./common.js').Command} */
export default {
  name: 'completion',
  summary: 'Print a shell completion script',
  usage: ['fwd completion bash|zsh|fish'],
  description: [
    'Install with:',
    '  bash   fwd completion bash > ~/.local/share/bash-completion/completions/fwd',
    '  zsh    fwd completion zsh > "${fpath[1]}/_fwd"   (or add `source <(fwd completion zsh)` to ~/.zshrc)',
    '  fish   fwd completion fish > ~/.config/fish/completions/fwd.fish',
  ].join('\n'),
  args: [1, 1],
  host: 'none',
  readonly: true,
  positionals: [Object.keys(generators)],

  async run({ args: [shell] }) {
    if (!Object.hasOwn(generators, shell)) {
      throw new FwdError(`Unknown shell "${shell}". Use ${Object.keys(generators).join(', ')}.`);
    }
    process.stdout.write(generators[/** @type {keyof typeof generators} */ (shell)](model()));
  },
};
